
services:
  triton_server:
    image: nvcr.io/nvidia/tritonserver:25.09-py3
    container_name: triton_server
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./triton_models:/models:rw
      - ./triton_logs:/logs:rw
    command: >
      tritonserver
      --model-repository=/models
      --model-control-mode=explicit
      --allow-http=true
      --allow-grpc=true
      --allow-metrics=true
      --log-verbose=1
      --log-file=/logs/triton.log
      --exit-on-error=false
      --strict-model-config=false
      --backend-config=python,shm-default-byte-size=1048576
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0-SNAPSHOT
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.0-SNAPSHOT
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:9.3.0-SNAPSHOT
    container_name: logstashc
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m" 
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - logstash_data:/usr/share/logstash/data
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    
  redis:
    profiles: ["client-search"]
    image: redis:7.4.8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass redis_admin
      --maxmemory 512mb
      --maxmemory-policy volatile-lru
    restart: unless-stopped
    networks:
      - redis_network

volumes:
    elastic_data:
    logstash_data:
    redis_data:
      driver: local

networks:
  elastic:
    driver: bridge
  redis_network:
    driver: bridge